name = "agentink"
main = "src/index.ts"
account_id = "49af3b7a36c06d76c04d8997c18b22e5"
compatibility_date = "2024-01-08"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
# RAPIDAPI_PROXY_SECRET = "your-secret-here"

[[d1_databases]]
binding = "DB"
database_name = "agent-ink-db"
database_id = "755d4b46-c458-4661-a04b-593ebe724e37"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "agent-ink-assets"

[ai]
binding = "AI"
